name: Edgware Martial Arts Academy
favicon: null
layout_spectrum: 1
typography_spectrum: 0.50582
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#004d7d'
    - '#ffc54b'
    - '#9f9f9f'
  brandStrength: 0.18715567258186638
  lightness: 0.7958645620383322
  saturation: 0.6678583277389407
  rhythmicContrast: 0.784276481019333
purpose: []
